# filepath: /Users/user/Documents/Projects/URL-Health-Monitor/url_health_monitor/docker-compose.yml
version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 'ssl://0.0.0.0:3000?key=/rails/config/ssl/localhost.key&cert=/rails/config/ssl/localhost.crt'"
    volumes:
      - .:/rails
      - ./config/ssl:/rails/config/ssl
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: development

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - web

volumes:
  postgres_data: